logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      ifortex:
        internship:
          authservice: DEBUG